% get delta_Yr vector
function delta_yr = GetDeltaYr(P, w, y, c)
delta_yr = cellfun(@(idx, w, y, c) GetYr(idx, w, y, c) - GetYr(idx - 1, w, y, c), ...
    num2cell(1:P), repmat({w}, 1, P), ...
    repmat({y}, 1, P), repmat({c}, 1, P))';
end

% function delta_yr = GetDeltaYr(P, t, w, Yp, c)
% delta_yr = cellfun(@(idx, t, w, Yp, c) GetYr(idx, t, w, Yp, c) - GetYr(idx - 1, t, w, Yp, c), ...
%     num2cell(1:P), repmat({t}, 1, P), repmat({w}, 1, P), ...
%     repmat({Yp}, 1, P), repmat({c}, 1, P))';
% end